### PR TITLE
Found A Fix

### PR DESCRIPTION
**Pull request by Gibberditoslumber**

### CODE REVIEW

**Comment by Gibberditoslumber** [comment]
```bash
Link: ApplicationMain
/usr/bin/ld: warning: libidn.so.12, needed by /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `pthread_setspecific@GLIBC_2.34'
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `dlopen@GLIBC_2.34'
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `pthread_rwlock_init@GLIBC_2.34'
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `fstat64@GLIBC_2.33'
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `pthread_rwlock_wrlock@GLIBC_2.34'
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `pthread_sigmask@GLIBC_2.32'
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `pthread_mutexattr_init@GLIBC_2.34'
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `pthread_testcancel@GLIBC_2.34'
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `pthread_condattr_setclock@GLIBC_2.34'
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `dlerror@GLIBC_2.34'
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `stat64@GLIBC_2.33'
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `pthread_getspecific@GLIBC_2.34'
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `pthread_create@GLIBC_2.34'
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `pthread_mutex_trylock@GLIBC_2.34'
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `sem_init@GLIBC_2.34'
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `pthread_mutexattr_destroy@GLIBC_2.34'
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `sem_destroy@GLIBC_2.34'
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `pthread_attr_setstacksize@GLIBC_2.34'
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `pthread_cancel@GLIBC_2.34'
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `pthread_mutexattr_settype@GLIBC_2.34'
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `pthread_join@GLIBC_2.34'
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `dlclose@GLIBC_2.34'
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `pthread_rwlock_rdlock@GLIBC_2.34'
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `pthread_key_delete@GLIBC_2.34'
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `sem_post@GLIBC_2.34'
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `pthread_once@GLIBC_2.34'
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `idna_to_ascii_8z@LIBIDN_1.0'
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `sem_wait@GLIBC_2.34'
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `pthread_rwlock_destroy@GLIBC_2.34'
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `pthread_key_create@GLIBC_2.34'
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `pthread_rwlock_unlock@GLIBC_2.34'
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `dlsym@GLIBC_2.34'
/usr/bin/ld: /home/avereyconley/haxelib/hxCodec/git/lib/vlc/lib/Linux/libvlccore.so.9: undefined reference to `lstat64@GLIBC_2.33'
collect2: error: ld returned 1 exit status
avereyconley@penguin:~/haxelib/FNF-PsychEngine$`

### SHIT

**Comment by Gibberditoslumber** [comment]
### SHIT

**Comment by BeastlyGhost** [comment]
reverted to the old libs already, if I find a fix for it i will push an update

**Comment by BeastlyGhost** [comment]
if you find a fix, tell me
also I recommend modifiying your own mp4handler.hx

appDir variable should be
`var appDir = #if !linux "file:///" + Sys.getCwd() + "/" #else "file://" + Sys.getCwd() #end;`

pDir variable should be
`pDir = #if !linux "file:///" #else "file://" #end;`

**Comment by BeastlyGhost** [comment]
you may also need to replace your files with [these](https://github.com/polybiusproxy/hxCodec/commit/c7ad40e01015858c3a4bb088cd143853b9aee507)

**Comment by Gibberditoslumber** [comment]
Newst hxCodec Lib So idk why it didn't work

**Comment by Gibberditoslumber** [comment]
> you may also need to replace your files with [these](https://github.com/polybiusproxy/hxCodec/commit/c7ad40e01015858c3a4bb088cd143853b9aee507)

um can you make another branch that has the [Haxelib Version](https://lib.haxe.org/p/hxCodec/)

**Pull request closed without merging**
